id = "moxer-icon-theme"
name = "Moxer Icon Theme"
version = "0.1.0"
schema_version = 1
authors = ["Navneet Lal Gupta <navneetlalg@gmail.com>"]
description = "Moxer Icon Pack"
repository = "https://github.com/navneetlalg/zed-moxer-icon-theme"
